version: '3.4'

services:

  qfileserverdb:
    image: "mcr.microsoft.com/mssql/server"

  qfileserver:
    image: ${DOCKER_REGISTRY-}qfileserver
    build:
      context: .
      dockerfile: QFileServer/Dockerfile
    depends_on:
      - qfileserverdb

  qfileserver.mvc:
    image: ${DOCKER_REGISTRY-}qfileservermvc
    build:
      context: .
      dockerfile: QFileServer.Mvc/Dockerfile
    depends_on:
      - qfileserver
